### ISSUE TITLE
Add links to changelly with our ref id in the URL

### ISSUE THREAD

**Issue by kazazor** [CoinsHero/coinshero#39]
* Should we have a button in each row to send the user to?
* Should we have somewhere special that says that you can buy there in USD & EUR? IMO that's one of the most powerful people wants to know when looking to but alt coins...
* Should we also give option to something else like `cex.io`? Also has a referrer plan like changelly..

Link: https://changelly.com/exchange/USD/BTC/1?ref_id=298522b89520

(This link sends by default the user to from USD to BTC with our link.. Probably a common use case..)

**Comment by kazazor** [comment]
Is blocked by: https://github.com/kazazor/coinsmarket/issues/52

**Comment by OmriAharon** [comment]
1. Added a button in each row with a link to Changelly
2. Added a small caption above the table to indicate USD & EU purchases are available
3. No `cex` at this point
